name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_cortex-a53
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/bcm27xx/bcm2710
            sdk_name: -sdk-23.05.5-bcm27xx-bcm2710_
          - arch: aarch64_cortex-a72
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/mvebu/cortexa72
            sdk_name: -sdk-23.05.5-mvebu-cortexa72_
          - arch: aarch64_generic
            sdk_url_path: http://downloads.openwrt.org/releases/23.05.5/targets/layerscape/armv8_64b
            sdk_name: -sdk-23.05.5-layerscape-armv8_64b_
          - arch: arm_arm1176jzf-s_vfp
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/bcm27xx/bcm2708
            sdk_name: -sdk-23.05.5-bcm27xx-bcm2708_
          - arch: arm_cortex-a15_neon-vfpv4
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/ipq806x/generic
            sdk_name: -sdk-23.05.5-ipq806x-generic_
          - arch: arm_cortex-a5-vfpv4
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/at91/sama5
            sdk_name: -sdk-23.05.5-at91-sama5_
          - arch: arm_cortex-a7_neon-vfpv4
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/bcm27xx/bcm2709
            sdk_name: -sdk-23.05.5-bcm27xx-bcm2709_
          - arch: arm_cortex-a8_vfpv3
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/sunxi/cortexa8
            sdk_name: -sdk-23.05.5-sunxi-cortexa8_
          - arch: arm_cortex-a9
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/bcm53xx/generic
            sdk_name: -sdk-23.05.5-bcm53xx-generic_
          - arch: arm_cortex-a9_neon
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/imx/cortexa9
            sdk_name: -sdk-23.05.5-imx-cortexa9_
          - arch: arm_cortex-a9_vfpv3-d16
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/mvebu/cortexa9
            sdk_name: -sdk-23.05.5-mvebu-cortexa9_
          - arch: arm_fa526
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/gemini/generic
            sdk_name: -sdk-23.05.5-gemini-generic_

          - arch: arm_xscale
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/kirkwood/generic
            sdk_name: -sdk-23.05.5-kirkwood-generic_
          - arch: i386_pentium
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/x86/legacy
            sdk_name: -sdk-23.05.5-x86-legacy_
          - arch: i386_pentium4
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/x86/generic
            sdk_name: -sdk-23.05.5-x86-generic_
          - arch: mips64_octeonplus
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/octeon/generic
            sdk_name: -sdk-23.05.5-octeon-generic_



          - arch: x86_64
            sdk_url_path: https://downloads.openwrt.org/releases/23.05.5/targets/x86/64
            sdk_name: -sdk-23.05.5-x86-64_

    env:
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      SDK_NAME: ${{ matrix.sdk_name }}
      ARCH: ${{ matrix.arch }}
      CACHE_DIR: ~/cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}:openwrt-v2ray:${{ env.ARCH }}:release:cache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:openwrt-v2ray:${{ env.ARCH }}:cache:

      - name: Setup CCache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}:openwrt-v2ray:${{ env.ARCH }}:release:ccache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:openwrt-v2ray:${{ env.ARCH }}:ccache:

      - name: Install Dependencies
        run: |
          sudo apt-get update && \
            sudo apt-get install -yq gettext libncurses5-dev rsync xsltproc

      - name: Prepare For Build
        run: |
          sdk_home="$(mktemp -d)"

          test -d ~/.ccache || mkdir -p ~/.ccache
          ln -sf ~/.ccache "$sdk_home/.ccache"

          echo "SDK_HOME=$sdk_home" >> $GITHUB_ENV
          echo "CONFIG_CCACHE=y" >> $GITHUB_ENV

      - name: Build package
        env:
          OPENWRT_GOLANG_COMMIT: ${{ secrets.OPENWRT_GOLANG_COMMIT }}
        run: sh compile.sh

      - name: Show CCache Status
        run: |
          eval "${{ env.SDK_HOME }}/staging_dir/host/bin/ccache -s"

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.ipk
            *.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify Release Publish
    runs-on: ubuntu-latest
    env:
      TRIGGER_URL: ${{ secrets.TRIGGER_URL }}
      TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
    needs: release
    steps:
      - name: Notify Jenkins
        run: |
          if [ -z "$TRIGGER_URL" ] ; then
            echo "::warning::No trigger url found, skip..."
            exit 0
          fi
          curl -X POST \
              -H "Content-Type: application/json; charset=utf-8" \
              -H "Authorization: Bearer $TRIGGER_TOKEN" \
              -d "{\"event\":\"release\",\"repository\":\"${{ github.repository }}\",\"ref\":\"${{ github.ref }}\"}" \
              "$TRIGGER_URL" || true
